version: '3.1'
services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=0199
    volumes:
      - parking-control:/var/lib/postgres
volumes:
  parking-control:
